# This file was *autogenerated* from the file detspeed.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_90 = Integer(90); _sage_const_7 = Integer(7); _sage_const_5 = Integer(5); _sage_const_0p081 = RealNumber('0.081'); _sage_const_5p811 = RealNumber('5.811'); _sage_const_20 = Integer(20); _sage_const_40 = Integer(40); _sage_const_2p760 = RealNumber('2.760'); _sage_const_1p054 = RealNumber('1.054'); _sage_const_60 = Integer(60); _sage_const_0p248 = RealNumber('0.248'); _sage_const_80 = Integer(80); _sage_const_7p869 = RealNumber('7.869'); _sage_const_2p5 = RealNumber('2.5'); _sage_const_10 = Integer(10); _sage_const_30 = Integer(30); _sage_const_50 = Integer(50); _sage_const_4p106 = RealNumber('4.106'); _sage_const_70 = Integer(70); _sage_const_100 = Integer(100); _sage_const_0p556 = RealNumber('0.556'); _sage_const_0p016 = RealNumber('0.016'); _sage_const_1p779 = RealNumber('1.779')# detspeed.sage; graph the speed of determinant calcuation
# run as: sage detspeed.sage it produces detspeed.pdf
# 2014-Nov-25 JH
rows = [_sage_const_10 , _sage_const_20 , _sage_const_30 , _sage_const_40 , _sage_const_50 , _sage_const_60 , _sage_const_70 , _sage_const_80 , _sage_const_90 , _sage_const_100 ]
secs = [_sage_const_0p016 , _sage_const_0p081 , _sage_const_0p248 , _sage_const_0p556 , _sage_const_1p054 , _sage_const_1p779 , _sage_const_2p760 , _sage_const_4p106 , _sage_const_5p811 , _sage_const_7p869 ]
data = zip(rows, secs)
g = scatter_plot(data, markersize=_sage_const_5 , facecolor='white', edgecolor='black', marker='o', figsize=_sage_const_2p5 , fontsize=_sage_const_7 , typeset='latex')
g.save("detspeed.pdf")
