TODO list for Linear Algebra http://joshua.smcvt.edu/linearalgebra 


* Look through bug reports

** subsectionoptional results in pdf errors in the log file about math shift,
leaves extra space at start of first sentence.



* New material

** SAGE? Lab manual?

** Cover art?

** Hestenes?

** Include handwritten versions of lower case Greek letters on flyleaf?

** Add Topic on error correcting codes?

** Add Topic on graphs are isomorphic iff their adjacency matrices are similar?

** Add Topic on coupled oscillators and normal modes, maybe with video?

* Refactor some code 

** Change vector look?
  http://www.reddit.com/r/LaTeX/comments/m4lxo/both_of_these_arrows_look_wrong_to_me_pic/

** XeLaTeX?

would allow a wide variety of fonts.  Does it limit graphics file input types,
etc?  See http://www.tug.org/pipermail/xetex/2011-August/021006.html

** Switch from MetaPost to Asymptote?

Like MetaPost but also 3D, and some sane control structures and data types?

*** including cleaning up loose files; find a place to put the .aux's 

Graphics files can have their own directory

other files need to be in the same dir as each other because of the need for
one file to read from another?  That is, cannot put files by chapter?

See http://tex.stackexchange.com/questions/37167/sorting-logs-into-different-folders

** Use the numprint package?
  http://www.ctan.org/pkg/numprint



* Try .cls

** Maybe various formats, different color schemes?

** Perhaps depending on command line choice?
  pdflatex euler book



* e-book format?
  Tried breqn but changing the equation* environment on line 1938 of gr1.tex
  to dmath* did not result in a break.  Puzzled.
