TODO list for Linear Algebra http://joshua.smcvt.edu/linearalgebra 


* Look through bug reports

** Do I need lemma 2.4 where it is?  Could I move it to after the defn
  of linear independence?

** In the index, make page references hyperlinks

** Do links in TOC work?

** subsectionoptional results in pdf errors in the log file about math shift,
leaves extra space at start of first sentence.



* New material

** topic on Google's algorithm?

** SAGE?

** Cover art?

** Cross product?

** Hestenes?

** Topic on magic squares? 
  http://mathoverflow.net/questions/33911/why-linear-algebra-is-funor

** Discuss writegood mode in 1st read me.  Mention that C-cG turns it off. 


* Refactor some code 

** mdframed

** mathtools
*** change all pmatrix to mat and all amatrix to amat, and also check all \vdots
to see if they need to be vdotswithin

** Change vector look?
  http://www.reddit.com/r/LaTeX/comments/m4lxo/both_of_these_arrows_look_wrong_to_me_pic/

** latexmk

** XeLaTeX?

would allow a wide variety of fonts.  Does it limit graphics file input types,
etc?  See http://www.tug.org/pipermail/xetex/2011-August/021006.html

** Asymptote?

Like MetaPost but also 3D, and some sane control structures and data types?

*** including cleaning up loose files; find a place to put the .aux's 

Graphics files can have their own directory

other files need to be in the same dir as each other because of the need for
one file to read from another?  That is, cannot put files by chapter?

See http://tex.stackexchange.com/questions/37167/sorting-logs-into-different-folders

** Use the numprint package?
  http://www.ctan.org/pkg/numprint



* Try .cls

** Maybe various formats, different color schemes?

** Perhaps depending on command line choice?
  pdflatex euler book



* e-book format?
